### ISSUE TITLE
Can't build: missing dependencies in golang.org/x/tools/go

### ISSUE THREAD

**Issue by dolmen** [sourcegraph/gostringer#4]
Some dependencies in [golang.org/x/tools/go](https://github.com/golang/tools/tree/master/go) do not exist anymore:
- `golang.org/x/tools/go/gcimporter`
- `golang.org/x/tools/go/exact`

**Comment by shurcooL** [comment]
Thanks for reporting!

I'll submit a PR that fixes this shortly.
